# Generated by Django 4.1 on 2023-07-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_life_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='chat_resp_time',
            field=models.CharField(default='100', max_length=100),
        ),
    ]
