# Generated by Django 4.1 on 2023-07-10 23:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_rename_wishlist_wishlist_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wishlist_model',
            new_name='wishlist',
        ),
    ]
